import Head from 'next/head';
import { Header } from './Header';

export const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700&family=Poppins:ital,wght@0,300;0,400;0,600;0,700;1,400&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="container max-w-6xl px-4 mx-auto md:px-6">
        <Header />
        {children}
      </div>
    </>
  );
};
